require("dotenv").config();
require("./config/database");

const EventType = require("./models/eventType");
const IncidentType = require("./models/incidentType");
const Event = require("./models/event");

(async function () {
  await EventType.deleteMany({});
  const eventType = await EventType.create([
    { type: "Crime" },
    { type: "Protest and Demonstration" },
    { type: "Public Disruptions" },
    { type: "Natural Disaster" },
    { type: "Missing Person" },
    { type: "Community Alert" },
    { type: "Others" },
  ]);

  await IncidentType.deleteMany({});
  const incident = await IncidentType.create([
    { eventType: eventType[0], incident: "Robbery" },
    { eventType: eventType[0], incident: "Burglary" },
    { eventType: eventType[0], incident: "Assault" },
    { eventType: eventType[0], incident: "Homicide" },
    { eventType: eventType[0], incident: "Vandalism" },
    { eventType: eventType[0], incident: "Theft" },
    { eventType: eventType[0], incident: "Fraud" },
    { eventType: eventType[0], incident: "Kidnapping" },
    { eventType: eventType[0], incident: "Domestic Violence" },
    { eventType: eventType[0], incident: "Sexual Assault" },
    { eventType: eventType[0], incident: "Child Abuse" },
    { eventType: eventType[0], incident: "Elder Abuse" },
    { eventType: eventType[0], incident: "Animal Abuse" },
    { eventType: eventType[0], incident: "Hate Crime" },
    { eventType: eventType[0], incident: "Arson" },
    { eventType: eventType[0], incident: "Drug-related" },
    { eventType: eventType[0], incident: "Human Trafficking" },
    { eventType: eventType[0], incident: "Cybercrime" },
    { eventType: eventType[0], incident: "Harassment" },
    { eventType: eventType[0], incident: "Stalking" },
    { eventType: eventType[0], incident: "Terrorism" },
    { eventType: eventType[1], incident: "Peaceful Protest" },
    { eventType: eventType[1], incident: "Violent Protest" },
    { eventType: eventType[1], incident: "Riot" },
    { eventType: eventType[1], incident: "March" },
    { eventType: eventType[1], incident: "Sit-in" },
    { eventType: eventType[1], incident: "Rally" },
    { eventType: eventType[1], incident: "Blockade" },
    { eventType: eventType[1], incident: "Civil Disobedience" },
    { eventType: eventType[1], incident: "Flash Mob" },
    { eventType: eventType[1], incident: "Political Rally" },
    { eventType: eventType[1], incident: "Enviromental Protest" },
    { eventType: eventType[1], incident: "Human Rights Protest" },
    { eventType: eventType[1], incident: "Strike" },
    { eventType: eventType[2], incident: "Traffic Jam" },
    { eventType: eventType[2], incident: "Roadblock" },
    { eventType: eventType[2], incident: "Construction" },
    { eventType: eventType[2], incident: "Power Outage" },
    { eventType: eventType[2], incident: "Water Outage" },
    { eventType: eventType[2], incident: "Gas Leak" },
    { eventType: eventType[2], incident: "Public Transport Delay" },
    { eventType: eventType[2], incident: "Accident" },
    { eventType: eventType[2], incident: "Car Accident" },
    { eventType: eventType[2], incident: "Train Accident" },
    { eventType: eventType[2], incident: "Plane Crash" },
    { eventType: eventType[3], incident: "Earthquake" },
    { eventType: eventType[3], incident: "Flood" },
    { eventType: eventType[3], incident: "Hurricane" },
    { eventType: eventType[3], incident: "Tornado" },
    { eventType: eventType[3], incident: "Wildfire" },
    { eventType: eventType[3], incident: "Fire" },
    { eventType: eventType[3], incident: "Explosion" },
    { eventType: eventType[3], incident: "Evacuation" },
    { eventType: eventType[4], incident: "Missing Child" },
    { eventType: eventType[4], incident: "Missing Adult" },
    { eventType: eventType[4], incident: "Missing Senior" },
    { eventType: eventType[4], incident: "Missing Pet" },
    { eventType: eventType[5], incident: "Suspicious Activity" },
    { eventType: eventType[5], incident: "Public Health Alert" },
    { eventType: eventType[5], incident: "Emergency Services Alert" },
    { eventType: eventType[5], incident: "Weather Alert" },
    { eventType: eventType[5], incident: "School Closure" },
    { eventType: eventType[5], incident: "Amber Alert" },
    { eventType: eventType[5], incident: "Silver Alert" },
    { eventType: eventType[6], incident: "Public Safety Announcement" },
    { eventType: eventType[6], incident: "Community Event" },
    { eventType: eventType[6], incident: "Fundraiser" },
    { eventType: eventType[6], incident: "Volunteer Opportunity" },
    { eventType: eventType[6], incident: "Charity Event" },
    { eventType: eventType[6], incident: "Lost Item" },
    { eventType: eventType[6], incident: "Found Item" },
  ]);

  await Event.deleteMany({});
  const event = await Event.create([
    {
      title: "Roberry on Elm St",
      address: "1234 Elm st",
      latitude: 29.7604,
      longitude: -96.3698,
      city: "Houston",
      state: "TX",
      country: "USA",
      zip: "77002",
      description: "Robbery on Elm St",
      user: "6647d4203cecb94f41d48747",
      reportDate: new Date("2019-03-14T00:00:00.000Z"),
      eventType: eventType[0],
      incidentType: incident[0],
    },
    {
      title: "Protest on Travis St",
      address: "600 Travis St",
      latitude: 29.7604,
      longitude: -95.3698,
      city: "Houston",
      state: "TX",
      country: "USA",
      zip: "77002",
      description: "Peacefull protest on Travis St",
      user: "6647d4203cecb94f41d48747",
      reportDate: new Date("2020-04-14T00:00:00.000Z"),
      eventType: eventType[1],
      incidentType: incident[1],
    },
    {
      title: "Roadblock on McKinney St",
      address: "1500 McKinney St",
      latitude: 29.7532,
      longitude: -95.3599,
      city: "Houston",
      state: "TX",
      country: "USA",
      zip: "77010",
      description: "Major roadblock on McKinney St",
      user: "6647d4203cecb94f41d48747",
      reportDate: new Date("2021-05-14T00:00:00.000Z"),
      eventType: eventType[2],
      incidentType: incident[2],
    },
    {
      title: "Report 2",
      address: "456 Oak St",
      latitude: 29.7525,
      longitude: -95.3704,
      city: "Houston",
      state: "TX",
      country: "USA",
      zip: "77003",
      description: "Vandalism on Oak St",
      user: "664873d0f13746d8d9ec0d88",
      reportDate: new Date("2021-07-22T00:00:00.000Z"),
      eventType: eventType[1],
      incidentType: incident[1],
    },
    {
      title: "Report 3",
      address: "789 Pine St",
      latitude: 29.7617,
      longitude: -95.3731,
      city: "Houston",
      state: "TX",
      country: "USA",
      zip: "77004",
      description: "Assault on Pine St",
      user: "664873d0f13746d8d9ec0d88",
      reportDate: new Date("2022-11-05T00:00:00.000Z"),
      eventType: eventType[2],
      incidentType: incident[2],
    },
    {
      title: "Report 4",
      address: "101 Maple St",
      latitude: 29.7583,
      longitude: -95.3763,
      city: "Houston",
      state: "TX",
      country: "USA",
      zip: "77005",
      description: "Burglary on Maple St",
      user: "664873d0f13746d8d9ec0d88",
      reportDate: new Date("2023-01-18T00:00:00.000Z"),
      eventType: eventType[3],
      incidentType: incident[3],
    },
  ]);

  console.log(event);

  process.exit();
})();
